// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 BiamOS Contributors
// ============================================================
// BiamOS — Capsules (Integrations) Schema
// ============================================================

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

/**
 * The `capsules` table stores all registered integration definitions.
 * Each integration maps an intent pattern to an API endpoint.
 * NOTE: Table name kept as 'capsules' to avoid DB migration.
 */
export const capsules = sqliteTable("capsules", {
    id: integer("id").primaryKey({ autoIncrement: true }),

    /** Unique component name, e.g. "WeatherWidget" */
    name: text("name").notNull().unique(),

    /** Human-readable description for intent matching */
    intent_description: text("intent_description").notNull(),

    /** API endpoint URL template */
    api_endpoint: text("api_endpoint").notNull(),

    /** MiniLM embedding vector (JSON string, 384 floats) */
    embedding: text("embedding"),

    /** Whether auto-generated by LLM Auto-Builder */
    is_auto_generated: integer("is_auto_generated", { mode: "boolean" })
        .notNull()
        .default(false),

    /** JSON auth config: { requiresAuth, authType?, ... } */
    api_config: text("api_config"),

    /** Group name for multi-endpoint integrations */
    group_name: text("group_name"),

    /** Whether integration is active */
    is_active: integer("is_active", { mode: "boolean" })
        .notNull()
        .default(true),

    /** Lifecycle status: "live" | "pending" | "auth_needed" | "inactive" */
    status: text("status").notNull().default("live"),

    /** Type: "api" (REST) or "web" (iframe embed) */
    integration_type: text("integration_type").notNull().default("api"),

    /** LLM-optimized tags for endpoint selection */
    endpoint_tags: text("endpoint_tags"),

    /** Auto-translated English tags */
    normalized_tags: text("normalized_tags"),

    /** HTTP method: GET, POST, PUT, PATCH, DELETE */
    http_method: text("http_method").notNull().default("GET"),

    /** JSON param schema: [{ name, type, required, in }] */
    param_schema: text("param_schema"),

    /** Group embedding vector (768 dims, Gemini) */
    group_embedding: text("group_embedding"),

    /** Sidebar icon (emoji, 1-4 chars) */
    sidebar_icon: text("sidebar_icon"),

    /** Short sidebar label (max ~10 chars) */
    sidebar_label: text("sidebar_label"),

    /** Human triggers for group-level filtering (pipe-separated) */
    human_triggers: text("human_triggers"),

    /** API triggers for endpoint-level selection (pipe-separated) */
    api_triggers: text("api_triggers"),

    /** JSON response mapping config */
    response_mapping: text("response_mapping"),

    /** Response data type: "image" | "video" | "text" | "list" | "mixed" */
    response_type: text("response_type"),

    /** Supported intent types (pipe-separated): "IMAGE|IMAGES|SEARCH" */
    supported_intents: text("supported_intents"),

    /** Whether this is a generic/utility API (deprioritized in routing) */
    is_generic: integer("is_generic").notNull().default(0),

    /** Health status: "healthy" | "degraded" | "offline" | "unchecked" */
    health_status: text("health_status").default("unchecked"),

    /** Reason for degraded/offline status */
    health_message: text("health_message"),

    /** ISO timestamp of last health check */
    health_checked_at: text("health_checked_at"),

    /** JSON array of allowed block types (null = all) */
    allowed_blocks: text("allowed_blocks"),

    /** Whether this is a pre-built template */
    is_template: integer("is_template", { mode: "boolean" })
        .notNull()
        .default(false),

    /** Template shop category: "data" | "content" | "tools" | "web" */
    template_category: text("template_category"),

    /** Short description for template cards */
    template_description: text("template_description"),
});

export type Integration = typeof capsules.$inferSelect;
export type NewIntegration = typeof capsules.$inferInsert;
